version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/SerilogMetrics*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: xoBgXlnyTeh+PMTdVWf6WkqJBwMSTx/5k9gikwuv15S/fiJjlPBfpU4eblJvGMoq
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: yiUveABinUJiYIbejeka2mPOlrG6vpmNDckhtrl+6C6/+bameXNwBGBUSCZBDRVK
  force_update: true
  artifact: artifacts/SerilogMetrics*.nupkg
  tag: v$(appveyor_build_version)
  on:
    branch: master